-- Таблица настроек модуля kbnet.starter
CREATE TABLE IF NOT EXISTS b_kbnet_starter_settings (
    ID INT(18) NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(255) NOT NULL,
    VALUE TEXT,
    SITE_ID CHAR(2) DEFAULT 's1',
    DESCRIPTION VARCHAR(500),
    TIMESTAMP_X DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UX_CODE_SITE (CODE, SITE_ID),
    KEY IX_CODE (CODE),
    KEY IX_SITE_ID (SITE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
